apiversion: v1
kind: pod
metadata:
     name: myapp
     lable: 
     app: myapp
spec:
   containers:  
     - name: my_container
      image: nginx
    ports:
      - containerport: 80



--------------

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80

